version: "3.8"

services:
  test-server:
    image: reinvanhaaren/test-server
    build:
      context: ./
      dockerfile: ./services/test-server/Dockerfile
    restart: unless-stopped
    ports:
      - 3000:3000
